Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/CyclomaticComplexity:
  Enabled: false

Style/IndentationWidth:
  Width: 4

Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/MethodLength:
  Max: 50
