Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false

Style/IndentationWidth:
  Width: 4

Style/MethodName:
  Enabled: false

Style/MethodLength:
  Max: 50
